### ISSUE TITLE
iPadOS 16.1 (20B5027f)无法使用

### ISSUE THREAD

**Issue by QianYushi** [crossutility/Quantumult-X#114]

**Comment by GengJian** [comment]
iOS 怎么安装的啊 有源码或者ipa么？

**Comment by Dokovic** [comment]
This bug has been fixed in the latest tf version, plz wait for the new update in AppStore.

**Comment by Dokovic** [comment]
> This bug has been fixed in the latest tf version, plz wait for the new update in AppStore.

Version 1.0.32 supports, make sure  you have updated Quantumult X

**Comment by BranGao** [comment]
Version 1.0.32 still cannot function properly under iPadOS 16.1 Beta1 iPadPro 11inch 1st gen

**Comment by liaowang11** [comment]
Buid number: 20B5045d not working.

**Comment by z-wentao** [comment]
Version 1.0.32 still cannot function properly under iPadOS 16.1 Beta1 iPadPro 12.9inch 1st gen
